stages:
  get_data:
    cmd: python get_data.py
    deps:
      - get_data.py
    outs:
      - data/penguins_clean.csv
  train:
    cmd: python train.py
    deps:
      - train.py
      - data/penguins_clean.csv
    metrics:
      - outputs/metrics.json:
          cache: false
    plots:
      - outputs/confusion_matrix.png:
          cache: false
